serve:
    port: 8080
    
spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/pruebaSpring
        username: postgres
        password: admin
        connectionTimeout: 20000
        minimumIdle: 1
        maxPoolSize: 1
        idleTimeout: 300000
        maxLifetime: 1200000
        autoCommit: true
        poolName: Crud-connection-pool
        driverClassName: org.postgresql.Driver
        
    jackson:
        date-format: yyyy-MM-dd
        time-zone: America/Bogota